theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "main"
    path: "/"
  repository_url: "https://github.com/UncleJunVIP/unclejunvip.github.io"
  
title: Uncle Jun VIP
description: "NextUI Paks that won't give you agita!"
